### ISSUE TITLE
images collector: Stop submitting size as a string

### ISSUE THREAD

**Issue by iainlane** [ubuntu/ubuntu-release-metrics#9]
I just had a look at this, not to make a graph but to see if the collector was working, and I saw that I couldn't work with the size field. After staring at it for a little bit I noticed that this is a string. I think we need to fix it to be an integer instead.

/cc @seb128

**Comment by seb128** [comment]
Right, fix proposed as #10 now

**Comment by iainlane** [comment]
Fixed via #10
